# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grumblr', '0004_userprofil'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofil',
            name='password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=420),
        ),
    ]
