# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grumblr', '0008_auto_20171019_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='followees',
        ),
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofil',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='followees',
            field=models.ManyToManyField(related_name='followees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
